### ISSUE TITLE
Cannot read property 'guess' of undefined 

### ISSUE THREAD

**Issue by zipme** [nuxt-community/guess-module#1]
Hi, I am trying to use this module but got this error:

```
TypeError: Cannot read property 'guess' of undefined
    at e.guess (e96bd19dbebbbac099cc.js:2)
    at 6a0ee43a16107d108e65.js:1
    at Array.<anonymous> (83e9f3a0721c8ff5d8f5.js:2)
    at Gt (83e9f3a0721c8ff5d8f5.js:2)
```

The nuxt.config:

```js
['@nuxtjs/guess', {
  GA: process.env.GA_VIEW_ID,
  jwt: {
    private_key: process.env.GA_PRIVATE_KEY,
    client_email: process.env.GA_CLIENT_EMAIL
  },
  period: {
    startDate: new Date('2018-09-01'),
    endDate: new Date('2018-10-09')
  },
  runtime: {
    delegate: true,
    prefetchConfig: {
      '4g': 0.3,
      '3g': 0.3,
      '2g': 0.3,
      'slow-2g': 0.3
    }
  }
}]
```

I am on nuxt 2.2.0

**Comment by clarkdo** [comment]
Could you install new version `0.1.2` and try again ?

**Comment by zipme** [comment]
@clarkdo that's quick! I just tried it but it's still the same error. The strange thing is, it worked before, but when I remove the node_modules folder and run `yarn install` again, then it stops working.

There is a related issue https://github.com/guess-js/guess/issues/83

**Comment by clarkdo** [comment]
The plugin should only work in `non-ssr` mode, could you provide a reproducible repo since it works fine for me with you config above.

**Comment by zipme** [comment]
@clarkdo I removed the module and update the config and add the plugin manually (baesd on https://github.com/daliborgogic/guess-nuxt) but is still the same error, I guess this is something in the `guess` library.

**Comment by zipme** [comment]
hi @clarkdo , after I disabled the pwa and remove all the cache the error seems to be gone, I guess it was the previous cached js caused the issue. Thanks for the help!!
